name: clickup-action
description: Github Action to change clickup task status based on branch.
inputs:
  CLICKUP_TEAM_ID:
    description: "ClickUp team id"
    required: true
  PR_TITLE:
    description: "Pull request title"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
