name: clickup-action
description: Github Action to change clickup task status based on branch.
inputs:
  CLICKUP_PERSONAL_TOKEN:
    description: "Environment"
    required: true
    default: "dev"
runs:
  using: "node16"
  main: "dist/index.js"
